# Generated by Django 2.1.15 on 2021-01-03 16:15
from django.db import migrations, transaction
import json
import os
print(os.getcwd())
def load_settings(apps, schema_editor):
    print("########## Started loading app settings")
    hangroo_setting = apps.get_model('commons', 'HangrooSetting')
    with open('commons/migrations/migration_data/hangroo_setting.json', 'r') as f:
        json_dict = json.load(f)
    for item in json_dict["hangroo_settings"]:
        try:
            print("[+] Loading into database : " + item["key_name"] + "  " + str(item["key_value"]))
            with transaction.atomic():
                hangroo_setting_object = hangroo_setting(
                    key_name=item["key_name"], 
                    key_value=item["key_value"],
                    description=item["description"]
                    )
                hangroo_setting_object.save()
        except Exception as e:
            print (e)
            print("[*] Failed to insert into db: " + item["key_name"] + "  " + str(item["key_value"]))


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_settings),
    ]
